import { SFSymbol } from "expo-symbols";


export  const Colors: string[] = [
  "#027BFD",
  "#4848FF",
  "#02A898",
  "#01A0F9",
  "#D8AB00",
  "#FE5900",
  "#01A0D2",
  "#FC3600",
  "#00B2BA",
  "#FF7B00",
  "#5AB300",
  "#008BFF",
  "#01A999",
  "#FE4054",
  "#2B63FF",
  "#A9AA00",
  "#DB42D3",
  "#F39A1D",
  "#F2212C",
];

export const emails: {
  id: string;
  sender: string;
  time: string;
  subject: string;
  preview: string;
  icon: SFSymbol;
  category: string;
}[] = [
  {
    id: 'p1',
    sender: 'Mom',
    time: '10:02',
    subject: 'Dinner this weekend?',
    preview: 'Hey sweetie, are you free this Sunday?',
    icon: 'person.fill',
    category: 'Primary',
  },
  {
    id: 'p4',
    sender: 'Spotify Friends',
    time: '2 days ago',
    subject: 'Your top songs of the month',
    preview: 'Here’s what you’ve been jamming to...',
    icon: 'music.note',
    category: 'Primary',
  },
  {
    id: 'p5',
    sender: 'Jason',
    time: 'Today',
    subject: 'Trip photos',
    preview: 'Sharing our road trip memories!',
    icon: 'photo.on.rectangle',
    category: 'Primary',
  },
  {
    id: 'p7',
    sender: 'Alex',
    time: 'Today',
    subject: 'Gym today?',
    preview: 'You still down for the 6pm slot?',
    icon: 'figure.walk',
    category: 'Primary',
  },
  {
    id: 'p10',
    sender: 'Team Alpha',
    time: 'Today',
    subject: 'Weekly meeting agenda',
    preview: 'Attached is our plan for tomorrow.',
    icon: 'calendar',
    category: 'Primary',
  },
  {
    id: 't1',
    sender: 'PayPal',
    time: 'Today',
    subject: 'You received $30.00 USD',
    preview: 'Ranea Brady sent you money.',
    icon: 'dollarsign.circle.fill',
    category: 'Transactions',
  },
  {
    id: 't2',
    sender: 'Stripe',
    time: 'Yesterday',
    subject: 'Payment completed',
    preview: 'Your payment of $10 was successful.',
    icon: 'creditcard.fill',
    category: 'Transactions',
  },
  {
    id: 't3',
    sender: 'Apple',
    time: 'Today',
    subject: 'Receipt from Apple',
    preview: 'You were charged $1.99 for iCloud.',
    icon: 'apple.logo',
    category: 'Transactions',
  },
  {
    id: 't4',
    sender: 'Amazon',
    time: 'Today',
    subject: 'Your order has shipped',
    preview: 'Track your order now.',
    icon: 'shippingbox.fill',
    category: 'Transactions',
  },
  {
    id: 't10',
    sender: 'Bank of America',
    time: 'Today',
    subject: 'Deposit notification',
    preview: 'A deposit of $200 was made.',
    icon: 'banknote.fill',
    category: 'Transactions',
  },

  {
    id: 'pr1',
    sender: 'Canva',
    time: 'Today',
    subject: 'Get 20% off your Pro plan!',
    preview: 'This deal ends soon — act fast.',
    icon: 'tag.fill',
    category: 'Promotions',
  },
  {
    id: 'pr2',
    sender: 'Nike',
    time: 'Yesterday',
    subject: 'New arrivals: Air Max 2025',
    preview: 'Explore the latest drop.',
    icon: 'shoeprints.fill',
    category: 'Promotions',
  },
  {
    id: 'pr3',
    sender: 'Udemy',
    time: 'Today',
    subject: 'Courses for $9.99 🔥',
    preview: 'Advance your career on a budget.',
    icon: 'book.fill',
    category: 'Promotions',
  },
  {
    id: 'pr5',
    sender: 'Starbucks',
    time: 'Today',
    subject: '2 for 1 drinks',
    preview: 'Bring a friend and save!',
    icon: 'cup.and.saucer.fill',
    category: 'Promotions',
  },
  {
    id: 'pr10',
    sender: 'Duolingo',
    time: 'Yesterday',
    subject: '30% off Super Duolingo',
    preview: 'Level up your learning with this offer.',
    icon: 'globe',
    category: 'Promotions',
  },
  {
    id: 'u1',
    sender: 'TikTok',
    time: 'Today',
    subject: 'New device login detected',
    preview: 'We noticed a new sign-in to your account.',
    icon: 'exclamationmark.shield.fill',
    category: 'Updates',
  },
  {
    id: 'u3',
    sender: 'Google',
    time: 'Today',
    subject: 'Security alert',
    preview: 'New sign-in to your account detected.',
    icon: 'lock.fill',
    category: 'Updates',
  },
  {
    id: 'u4',
    sender: 'Dropbox',
    time: 'Today',
    subject: 'Files added to shared folder',
    preview: 'Your team uploaded new content.',
    icon: 'folder.fill.badge.plus',
    category: 'Updates',
  },
  {
    id: 'u6',
    sender: 'Zoom',
    time: 'Today',
    subject: 'Meeting starts in 10 minutes',
    preview: 'Join now to avoid being late.',
    icon: 'video.fill',
    category: 'Updates',
  },
  {
    id: 'u9',
    sender: 'Figma',
    time: 'Today',
    subject: 'Your design was commented on',
    preview: 'Someone left feedback on Frame 2.',
    icon: 'pencil.tip.crop.circle',
    category: 'Updates',
  },
];
